### ISSUE TITLE
status.py: Last Reward calculation is wrong?

### ISSUE THREAD

**Issue by GuybrushX** [matsuro-hadouken/casper-tools#52]
Normally my rewards per ERA are about 10 CSPR. I transferred and self staked some more CSPR to my node wallet and now the Last Reward shows 10 + the self staked CSPR -> I think that is wrong?

**Comment by RapidMark** [comment]
Yea, that's just showing the increase from one era to another... which is actually correct except when your bond changes... I figured it was OK, because 99.99% of the time you're not increasing your bond... The Idea was to compare it against what the data is showing as a reward, vs what you actually got.

But I can change it if you think it's mis-represented

**Comment by GuybrushX** [comment]
I think it does destroy the stats completely with each staking. Especially now when a lot more delegation is happening since the new UI was released for (un-)staking. Each delegation will mess up the average and unstaking probably, too?

As another example right now I see a 7-figure as Last Reward and a few million percent of yearly rewards which would be very nice but totally misleading ;-)

Just to be clear I'm talking about the "Casper Validator Info -> Last Reward" stats.

**Comment by RapidMark** [comment]
Try it now... I'm now getting the value from the blockchain, instead of calculating between previous bond amounts

**Comment by GuybrushX** [comment]
Thank you :-)

I need to watch or maybe test on my testnet node but could take some time until I have some spare time for it.

**Comment by matsuro-hadouken** [comment]
We believe reward calculation should be correct by now. Inactive, closed.
